In [162]:
import pandas as pd
import numpy as np
import sys
import importlib.util
import os

Read file input.txt with path to data (.csv), operations, and percentace list

In [163]:
with open("input.txt", "r") as file:
    lines = [line.strip() for line in file if not line.lstrip().startswith("#")]

lines

['BostonHousingN.csv',
 '.',
 'implications.py',
 'Fodora',
 'operations.py',
 'T_F',
 '0,0,0,0,0,1,0,0,0,0,2,15,0']

In [164]:

module_path = lines[1]
if os.path.exists(module_path):
    sys.path.append(module_path)
else:
    raise FileNotFoundError(f"Path {module_path} does not exist!")
module_name =  lines[2][0:-3]
imp = importlib.import_module(module_name)
module_name =  lines[4][0:-3]
ope = importlib.import_module(module_name)

In [165]:
data = pd.read_csv(lines[0],sep=",")
data

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.000000,0.18,0.067815,0.0,0.314815,0.577505,0.641607,0.269203,0.000000,0.208015,0.287234,1.000000,0.089680,0.422222
1,0.000236,0.00,0.242302,0.0,0.172840,0.547998,0.782698,0.348962,0.043478,0.104962,0.553191,1.000000,0.204470,0.368889
2,0.000236,0.00,0.242302,0.0,0.172840,0.694386,0.599382,0.348962,0.043478,0.104962,0.553191,0.989737,0.063466,0.660000
3,0.000293,0.00,0.063050,0.0,0.150206,0.658555,0.441813,0.448545,0.086957,0.066794,0.648936,0.994276,0.033389,0.631111
4,0.000705,0.00,0.063050,0.0,0.150206,0.687105,0.528321,0.448545,0.086957,0.066794,0.648936,1.000000,0.099338,0.693333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.000633,0.00,0.420455,0.0,0.386831,0.580954,0.681771,0.122671,0.000000,0.164122,0.893617,0.987619,0.219095,0.386667
502,0.000438,0.00,0.420455,0.0,0.386831,0.490324,0.760041,0.105293,0.000000,0.164122,0.893617,1.000000,0.202815,0.346667
503,0.000612,0.00,0.420455,0.0,0.386831,0.654340,0.907312,0.094381,0.000000,0.164122,0.893617,1.000000,0.107892,0.420000
504,0.001161,0.00,0.420455,0.0,0.386831,0.619467,0.889804,0.114514,0.000000,0.164122,0.893617,0.991301,0.131071,0.377778
505,0.000462,0.00,0.420455,0.0,0.386831,0.473079,0.802266,0.125072,0.000000,0.164122,0.893617,1.000000,0.169702,0.153333

In [166]:
headers = list(data)
headers, header_to_compare = headers[:-1], headers[-1]
headers

['crim',
 'zn',
 'indus',
 'chas',
 'nox',
 'rm',
 'age',
 'dis',
 'rad',
 'tax',
 'ptratio',
 'b',
 'lstat']

In [167]:
shape = (data.shape[0], data.shape[1]-1)

A = (data.iloc[:,:shape[1]])
b = (data.iloc[:,shape[1]])

In [168]:
dir(imp)[0:4], "..."

(['Einsteina', 'Fodora', 'Godela', 'Goguena'], '...')

In [169]:
u=[]
matrix_solution = matrix_solution = np.zeros(shape)

for i in range(shape[0]):
    for j in range(shape[1]):
        matrix_solution[i, j] = imp.implication_function(lines[3], A.iloc[i, j], b[j])
for j in range(shape[1]):
    u.append(round(min(matrix_solution[:, j]),2))
print("the greatest sulution Ax<=b\nu^T",u)

the greatest sulution Ax<=b
u^T [0.42, 0.37, 0.66, 0.63, 0.69, 0.53, 0.4, 0.49, 0.26, 0.31, 0.22, 0.31, 0.37]

### Calculate the minimum with each column omitted:
- for each column has to be defined percent of indexes to remove
- if none then 0%
- solution is matrix_solution

In [152]:
#upper
# percentage_for_each_column= list(map(int, lines[6].split(","))) # %
# indexes_to_remove = set()
# for j in range(shape[1]):
#     indexes_to_remove.update(A.iloc[:,j].sort_values(ascending=False).index[0:int(shape[0]*percentage_for_each_column[j]/100)])
# len(indexes_to_remove)

173

In [170]:
#lower
percentage_for_each_column= list(map(int, lines[6].split(","))) # %
indexes_to_remove = set()
for j in range(shape[1]):
     indexes_to_remove.update(A.iloc[:,j].sort_values(ascending=True).index[0:int(shape[0]*percentage_for_each_column[j]/100)])
len(indexes_to_remove)

88

In [171]:
A_submatrix = A.drop(axis='index', index=list(indexes_to_remove)).copy()
b_submatrix = b.drop(axis='index', index=list(indexes_to_remove)).copy()
A_submatrix = A_submatrix.reset_index(drop=True)
b_submatrix = b_submatrix.reset_index(drop=True)
#A_submatrix
#b_submatrix

In [172]:
u=[]
shape_submatrix = A_submatrix.shape
matrix_solution = np.zeros(shape_submatrix)
for i in range(shape_submatrix[0]):
    for j in range(shape_submatrix[1]):
        matrix_solution[i, j] = imp.implication_function(lines[3], A_submatrix.iloc[i, j], b_submatrix[j])
for j in range(shape[1]):
    u.append(round(min(matrix_solution[:, j]),2))
print("the greatest sulution A(submatrix)x<=b(submatrix)\nu^T=",u)

the greatest sulution A(submatrix)x<=b(submatrix)
u^T= [0.42, 0.37, 0.66, 0.63, 0.69, 0.53, 0.4, 0.49, 0.26, 0.31, 0.22, 0.31, 0.37]

In [173]:
b_to_check = np.zeros((shape[0],1))
for i in range(shape[0]): 
    wsolution_row = []
    for j in range(shape[1]): 
        wsolution_row.append(ope.operation_function(lines[5],A.iloc[i,j], u[j]))
    wsolution = max(wsolution_row)
    b_to_check[i,0] = wsolution
#print(b_to_check)

### Remove rows from the matrix, such that a_ij*matrix_solution_minimum>b_

In [174]:
list_of_correct_rows = []
list_of_not_correct_rows = []
for i in range(len(b_to_check)):
    if b_to_check[i,0] > data[header_to_compare][i]:
        list_of_correct_rows.append(i)
    else: list_of_not_correct_rows.append(i)
# Amount of incorrect and correct rows
"Correct: ", len(list_of_correct_rows),"Incorrect:", len(list_of_not_correct_rows)

('Correct: ', 397, 'Incorrect:', 109)

In [175]:
data_correct = data.copy()
data_correct= data_correct.drop(axis='index', index=list_of_not_correct_rows)
data_correct

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.000000,0.180,0.067815,0.0,0.314815,0.577505,0.641607,0.269203,0.000000,0.208015,0.287234,1.000000,0.089680,0.422222
1,0.000236,0.000,0.242302,0.0,0.172840,0.547998,0.782698,0.348962,0.043478,0.104962,0.553191,1.000000,0.204470,0.368889
5,0.000264,0.000,0.063050,0.0,0.150206,0.549722,0.574665,0.448545,0.086957,0.066794,0.648936,0.992990,0.096026,0.526667
6,0.000921,0.125,0.271628,0.0,0.286008,0.469630,0.656025,0.402923,0.173913,0.236641,0.276596,0.996722,0.295254,0.397778
7,0.001554,0.125,0.271628,0.0,0.286008,0.500287,0.959835,0.438387,0.173913,0.236641,0.276596,1.000000,0.480684,0.491111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.000633,0.000,0.420455,0.0,0.386831,0.580954,0.681771,0.122671,0.000000,0.164122,0.893617,0.987619,0.219095,0.386667
502,0.000438,0.000,0.420455,0.0,0.386831,0.490324,0.760041,0.105293,0.000000,0.164122,0.893617,1.000000,0.202815,0.346667
503,0.000612,0.000,0.420455,0.0,0.386831,0.654340,0.907312,0.094381,0.000000,0.164122,0.893617,1.000000,0.107892,0.420000
504,0.001161,0.000,0.420455,0.0,0.386831,0.619467,0.889804,0.114514,0.000000,0.164122,0.893617,0.991301,0.131071,0.377778
505,0.000462,0.000,0.420455,0.0,0.386831,0.473079,0.802266,0.125072,0.000000,0.164122,0.893617,1.000000,0.169702,0.153333

In [176]:
data_not_correct = data.copy()
data_not_correct = data_not_correct.drop(axis='index', index=list_of_correct_rows)
data_not_correct

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
2,0.000236,0.000,0.242302,0.0,0.172840,0.694386,0.599382,0.348962,0.043478,0.104962,0.553191,0.989737,0.063466,0.660000
3,0.000293,0.000,0.063050,0.0,0.150206,0.658555,0.441813,0.448545,0.086957,0.066794,0.648936,0.994276,0.033389,0.631111
4,0.000705,0.000,0.063050,0.0,0.150206,0.687105,0.528321,0.448545,0.086957,0.066794,0.648936,1.000000,0.099338,0.693333
12,0.000983,0.125,0.271628,0.0,0.286008,0.446062,0.371782,0.392956,0.173913,0.236641,0.276596,0.983862,0.385762,0.371111
15,0.006981,0.000,0.281525,0.0,0.314815,0.435524,0.552008,0.306359,0.130435,0.229008,0.893617,0.996772,0.185982,0.331111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,0.063658,0.000,0.646628,1.0,0.506173,0.598199,0.967044,0.020651,1.000000,0.914122,0.808511,0.945610,0.055188,1.000000
370,0.073423,0.000,0.646628,1.0,0.506173,0.662004,0.974253,0.006620,1.000000,0.914122,0.808511,0.987770,0.033940,1.000000
371,0.103698,0.000,0.646628,0.0,0.506173,0.508718,1.000000,0.003592,1.000000,0.914122,0.808511,0.922462,0.215232,1.000000
372,0.092851,0.000,0.646628,1.0,0.582305,0.443380,0.892894,0.000000,1.000000,0.914122,0.808511,0.876393,0.197296,1.000000
494,0.003071,0.000,0.338343,0.0,0.411523,0.453152,0.408857,0.113859,0.217391,0.389313,0.702128,1.000000,0.327263,0.433333

In [177]:
data_correct.to_csv(lines[1]+"\\"+"solution_correct.csv")
data_not_correct.to_csv(lines[1]+"\\"+"solution_incorrect.csv")